import type { Metadata } from "next";
import "./ui/global.scss";
import { openSans } from "./ui/fonts";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} antialiased`}
      >
        <h1 className={`text-blue-500 ${openSans.className}`}>I'm blue text in the app layout. My font is Open Sans.!</h1>
        {children}
      </body>
    </html>
  );
}
